
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  labels:
    app: comentario-app
    role: persistency
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-claim
  labels:
    app: comentario-app
    role: persistency
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi

