
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: comentario-app
    role: database
spec:
  type: ClusterIP
  selector:
    app: comentario-app
    role: database
  ports:
  - name: database-service-port
    port: 3306
    targetPort: database-port

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: comentario-app
    role: backend
spec:
  type: ClusterIP
  selector:
    app: comentario-app
    role: backend
  ports:
  - name: backend-service-port
    port: 80
    targetPort: backend-port

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: comentario-app
    role: frontend
spec:
  type: LoadBalancer
  selector:
    app: comentario-app
    role: frontend
  ports:
  - name: frontend-service-port
    port: 80
    targetPort: frontend-port

